name: Build Master
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run './build.sh Test'
        run: ./build.sh Test
    - uses: actions/upload-artifact@v1
        with:
        name: test-results
        path: artifacts/test-results
    - uses: actions/upload-artifact@v1
        with:
        name: coverage-report.zip
        path: artifacts/coverage-report.zip
  
